baseurl = "http://www.wmedrano.dev"
title = "wmedrano dot dev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
  style = "nord"

[params]
  author = "Will Medrano"
  info = "Software Engineer"
  description = "Will's personal website"
  keywords = "blog,software,developer"
  avatarurl = "profile.jpg"
  since = 2023
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/wmedrano"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Configs"
  weight = 2
  url  = "configs"
[[menu.main]]
  name = "Ideas"
  weight = 3
  url = "ideas/"
[[menu.main]]
  name = "About"
  weight = 4
  url = "about/"
