title: wmedrano dot dev
baseURL: 'https://wmedrano.dev'
theme: fuji
enableEmoji: true
enableRobotsTXT: true
languageCode: en
defaultContentLanguage: en
summaryLength: 100
paginate: 10

outputFormats:
  SearchIndex:
    isPlainText: true
    notAlternative: true
    mediaType: application/json
    path: /search/
outputs:
  home: ["HTML", "RSS", "SearchIndex"]

permalinks:
  post: '/:section/:filename/'

params:
  author: Will Medrano
  subTitle: wmedrano dot dev
  defaultTheme: auto
  sourceURL: 'https://github.com/wmedrano/wmedrano.dev'
  showWordCounter: true
  showReadTime: true
  hideNoTagList: false
  showLicenseInFooter: false
  showLicense: true
  showToc: true
  copyrightStartYear: '2023'
  description: Will's blog site.
  og: /img/og.png
  mainSections:
    - posts
  license: CC BY-NC-SA 4.0
  licenseLink: 'http://creativecommons.org/licenses/by-nc-sa/4.0/'
  lazyPlaceholder: /assets/lazyload/dsrca_loading_480x270.svg
  lazyPlaceholderRow: /assets/lazyload/dsrca_loading_960x270.svg
  lazyPlaceholderCol: /assets/lazyload/dsrca_loading_480x540.svg
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3
taxonomies:
  tag: tags
menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Search
      url: /search/
      weight: 2
    - name: About
      url: /about/
      weight: 3
  link:
    - name: GitHub
      url: 'https://github.com/wmedrano'
      weight: 1
    - name: Donate on ko-fi
      url: 'https://ko-fi.com/wmedrano'
      weight: 2
build:
  noJSConfigInAssets: true
security:
  enableInlineShortcodes: true
