baseURL: 'https://wmedrano.dev'
theme: salinger
title: wmedrano dot dev
copyright: will.s.medrano@gmail.com
pygmentsstyle: github
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
ignoreErrors:
  - error-remote-getjson
params:
  DateFormat: January 01 2006
  description: >-
    I'm a software engineer.
  header: "wmedrano dot dev"
  keywords:
    - developer
    - coding
    - maker
  showHeaderOnHomepage: true
  twemoji: true
  text404: Page not found.
  social:
    - name: github
      url: 'https://github.com/wmedrano'
      icon: fa fa-github
    - name: ko-fi
      url: 'https://ko-fi.com/wmedrano'
      icon: fa fa-coffee
menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: About
      url: /about/
      weight: 3
taxonomies:
  tag: tags
  category: categories
markup:
  goldmark:
    renderer:
      unsafe: true
