baseurl = "http://www.wmedrano.dev"
title = "wmedrano dot dev"
theme = "PaperMod"
languagecode = "en"
defaultcontentlanguage = "en"

[markup.highlight]
  style = "nord"
  codeFences = true
  guessSyntax = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[params]
  env = "production"
  mainSections = ["posts"]
  ShowShareButtons = true
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.assets]
  disableHLJS = true

[params.profileMode]
  enabled = true
  imageUrl = "profile.jpg"

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts"

[[params.profileMode.buttons]]
  name = "Living Programs"
  url = "/living-programs"

[[params.profileMode.buttons]]
  name = "About Me"
  url = "/about"

[[params.socialIcons]]
  name = "Github"
  url = "https://github.com/wmedrano"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# Menu links
[[menu.main]]
  name = "Posts"
  id = "posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Living Programs"
  id = "living-programs"
  title = "Living Programs"
  weight = 2
  url  = "living-programs/"
[[menu.main]]
  name = "Drafts"
  id = "drafts"
  weight = 3
  url = "drafts/"
[[menu.main]]
  name = "Search"
  id = "search"
  weight = 4
  url = "search/"
[[menu.main]]
  name = "About"
  id = "about"
  weight = 5
  url = "about"
