baseURL: 'https://wmedrano.dev'
languageCode: en-us
title: wmedrano dot dev
theme: archie
copyright: © will.s.medrano@gmail.com
pygmentsstyle: github
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
paginate: 5
params:
  mode: auto
  useCDN: false
  subtitle: Will's programming blog
  mathjax: true
  katex: true
  social:
    - name: GitHub
      icon: github
      url: 'https://github.com/wmedrano'
    - name: Ko-Fi
      icon: coffee
      url: 'https://ko-fi.com/wmedrano'
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
