version: "3.9" # optional since v1.27.0
networks:
  # Created with: docker network create web
  web:
    external: true
  # Created with: docker network create --internal internal
  internal:
    external: false
    driver: bridge
services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80" # http port
      - "443:443" # https port
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile # Main config
      - ./caddy/config:/config # Config volume, unused
      - ./caddy/data:/data # Data volume, unused
    networks:
      - web
      - internal
  jupyter:
    image: wmedrano_jupyter:latest
    volumes:
      # Contains jupyter lab config, including authentication.
      - ./jupyter/.jupyter:/root/.jupyter
      # Volume containing notebooks.
      - ./jupyter/app:/usr/src/app
    networks:
      - internal
  gitea:
    image: gitea/gitea:1.16.5
    environment:
      - USER_UID=1000
      - USER_GUID=1000
    restart: always
    volumes:
      - ./gitea/data:/data # Persistent data for gitea.
      - /etc/timezone:/etc/timezone:ro # Time configuration.
      - /etc/localtime:/etc/localtime:ro # Time configuration.
    ports:
      - "21895:22"
    networks:
      - web
