#+title: New Years Resolution Evaluation - Reading
#+author: Will Medrano
#+date: 2024-12-18

* Goal

My goal this year was to read more books. One a month. To be honest, the
planning was very fuzzy so I can hardly remember what I set out to do. The
brainstorming featured piano, personal projects, drawing, and reading. By the
time I remembered in November, the most reasonable seemed to be reading a book a
month, making me 10 books behind.

* Reasoning

So why reading? My past goals have been related to improvement, usually with
some aspect of work. I've obtained a consistent exercise routine, optimized my
productivity, improved my planning & design skills, and documentation. At this
point, I feel like I produce pretty good artifacts but I have the one shame, I
don't read good.

There is some documentation that I read religiously [fn:favorite-documentation],
but for the most part, I hack and slash to get what I want. This is my primary
approach. I don't have any plans to change it, but I think there's headroom to
improve what I take away from technical documentation.

So, why not set a goal on reading documentation and technical material? For one,
I've liked the idea of adding some fiction reading to my routine. I haven't
voluntarily read a work of fiction in ... at least 15 years. And for two, why
can't I read a goddamn book! I can scroll through heaps of Hacker News, YouTube,
Reddit, audiobooks but only manage to read about one or two non fiction books
per year.

* Progress

By the time I remembered my reading goal in November, I had read 0.1 books. It
is now mid December and I have finished 5 books. This puts me at a 41% with a
trajectory of finishing at 50% with a moderate possibility of 100% depending on
how I spend my weekend.

file:books.png

So, based on the numbers, I did not do well this year. On the other hand, I did
also read some papers sometime in the middle of the year and the reading of
fiction has improved my ability to focus.

* Findings

** Reading Speed

I can now read pretty fast *sometimes*.

Earlier this year, I tried to slog through "The Metamorphosis & Other Stories"
by Franz Kafka. The style and ideas from the short stories were psychedelic and
delightful. However, I managed to read only 10% after a few days and struggled
to keep my mind focused. My second attempt in November was easier but it still
required plenty of discipline. However, as the book went on, it became easier
for me to keep focus. I finished the book in roughly 1.5 weeks (I think). Given
my effort, this was frustratingly slow. Reading long stretches without zoning
out was exhausting.

The most recent read, "Hollow Kingdom" by Kira Jane Buxton, took me 6 sittings
across 2 days. This was a nice improvement over the 1.5 weeks reading Kafka's
short stories which were roughly half as long. Anecdotally, I found it easier to
focus and was able to read longer without needing a break. Will this translate
to work-related readings? Probably, I think, I'll see once I get back from my
short vacation.

** School and Time Sucked the Fun out of Fiction

This is perhaps the first time I have voluntarily completed a fiction novel
since middle school. The first novel I read was "Tuck Everlasting" in 4th
grade. Although I didn't like the timelines (who does), I enjoyed the
experience. Over the years, I would get assigned books and even read more
related books. However, sometime in high school, I dropped reading for fun due
to time constraints and the focus of reading books. Books were read to hunt for
themes and symbols in order to churn out generic essays highlighting the correct
answer [fn:school-reading-requirements].

With the latest readings, I didn't need to be on the lookout for the right
answers to an upcoming test. In 1984, I didn't have to care at all about what
the "Glass Paperweight" represented, and frankly it wasn't that good of a symbol
anyways.

**Spoilers** When Winston wondered why the party operated, my cynical mind said,
"it doesn't matter, they just do it to do it you romantic idiot". I never
expected the book to try to answer the question so clearly. I was surprised when
my stupid take was validated by the villain, as "The Party seeks power entirely
for its own sake".

It's much more fun when there's no pressure of an upcoming test or
assignment. Without the weight, I feel like I'm diving just as deep, possibly
deeper, than I used to. I managed to have fun reading all the books on my
list[fn:poe].

** El Enemigo Returns

This wasn't really a learning. I've known this for a while. As I'm trying to
read and need a break, the first thing that I reach for is... my phone. More
insidious, I look up a word and then find myself on Wikipedia and then somehow
on YouTube?! When YCombinator expound the beauty of startups providing huge
value and name the iPhone, I can't help but to throw up. The dopamine device has
stolen way too much attention.

* Conclusion

So how did I do? I did pretty well in the past 2 months. Although I should've
put more effort at the start of the year, I did read a lot and it was
enjoyable. Next year I will focus on my Piano skills, but will probably continue
to read[fn:post-blog-readings] and combat the urge to burn time on form content.

[fn:favorite-documentation] Some of my favorite documentation includes [[https://www.gnu.org/software/guile/manual/html_node/][The Guile Reference
Manual]] and [[https://wiki.libsdl.org/SDL3/FrontPage][SDL Wiki]].

[fn:school-reading-requirements] Although this may sound like a harsh critique, I'm glad that
school forced me to read. Praying that I would read for fun would not
have improved my literacy.

[fn:poe] After reading the first short story, I didn't want to spend
any more time translating Poe's overindulgent language.

[fn:post-blog-readings] I read "The Trial" by Franz Kafka before the end of the
year which technically puts me at 6 out of 12 for the year.
