#+TITLE: Literate Programming
#+AUTHOR: Will Medrano
#+HUGO_BASE_DIR: ./..
#+HUGO_EXPORT_DATE: 2023-04-20
#+FILETAGS: emacs

* Literate Programming
:PROPERTIES:
:EXPORT_TITLE: Experience with Literate Programming in Org Mode
:EXPORT_FILE_NAME: literate-programming
:EXPORT_DATE: 2023-04-20
:CUSTOM_ID: LiterateProgramming-fe91zi71ktj0
:END:

#+BEGIN_SUMMARY
By looking into Org Mode, I managed to sidetrack myself into writing my Emacs
Configuration as a literate program.
#+END_SUMMARY

** What is Emacs and Org Mode?
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingWhatisEmacsandOrgMode-2u91zi71ktj0
:END:

*** Emacs
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingWhatisEmacsandOrgModeEmacs-ykahlbp0otj0
:END:

Emacs is a (very old) text editor that is highly customizable. The configuration
is one of the main appeals of Emacs. Emacs is configured using Emacs Lisp and
pretty much everything in Emacs is extensible. The documentation for Emacs is
also fantastic and built directly into the editor. Don't know what a key will
do? Use =C-h k <key that you want to know>= and Emacs will open up a help window
with:

- The function that is run on that keypress.
- Documentation for the function.
- The keymap that defines the binding.
- A link to the source code for the function.

Need to know what a function does, type =C-h f <function>= to open up its
documentation. Configuring Emacs feels more like writing code than it does
writing configuration. This is why I have spent countless hours configuring
Emacs as opposed to the bare minimum configuring VSCode. Emacs also has a large
community of developers that have created several packages; most popular
packages are published on [[https://melpa.org/#/][Melpa]].

Although I like Emacs, I haven't been using it much recently. This is in part to
its poor integration into my tools at work and also because its LSP integration
is not as polished as VSCode.

*** Org Mode
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingWhatisEmacsandOrgModeOrgMode-xjqj3bp0otj0
:END:

Org Mode is a note-taking and list management system. Superficially, it is
similar to Markdown but predates it by about a year (2003 vs 2004). I am just
now beginning to look into Org Mode to organize my life, but I plan to
incorporate it into most aspects of my note taking and task tracking.

** Journey To Literate Programming
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingJourneyToLiterateProgramming-fba1zi71ktj0
:END:

For my recent return to Emacs, I wanted to focus on learning Org Mode. However,
I first needed to remake my Emacs configuration! Conveniently, it turns out that
Org Mode is one of the supported ways of writing an Emacs configuration. Writing
in Org Mode is also often considered a form of literate programming.

** What Is Literate Programming?
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingWhatIsLiterateProgramming-5ra1zi71ktj0
:END:

Literate programming  is a methodology that focuses on create a literate
document. This is opposed to the traditional paradigm in which the code is a
first class citizen and documentation is secondary. Modern day tooling that
enables this includes Jupyter Notebooks and Org Mode.

From [[https://www.literateprogramming.com][literateprogramming.com]] by Donald Knuth:

#+BEGIN_QUOTE
... Instead of imagining that our main task is to instruct a computer what to
do, let us concentrate rather on explaining to human beings what we want a
computer to do.
#+END_QUOTE

** Emacs Lisp in Org Mode Experience
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingEmacsLispinOrgModeExperience-77b1zi71ktj0
:END:

At first, writing an Emacs Lisp program with Org Mode felt pretty normal and
everything worked as expected. However, I noticed a deficiency once I exported
the Org file to HTML. Although I thought that the layout of my code made sense,
the final HTML didn't feel high quality. After some refactoring the document
started to become more readable. And then, it clicked. When adding a new feature
to my configuration, I started thinking more in terms of the literate part. When
adding a new feature, my first thought is now to take a look at the outline and
find the place where it fits best.

** Result
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingResult-nmb1zi71ktj0
:END:

The final literate program can be read at
[[https://www.wmedrano.dev/literate-programs/emacs-config]] with the source code
residing in [[https://github.com/wmedrano/emacs-config]].

** Observations
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingObservations-h1c1zi71ktj0
:END:

*** Narrative
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingObservationsNarrative-ygc1zi71ktj0
:END:

Literate programming focuses on readability front and foremost. When adding
features to my Emacs configuration, I first have to envision how it fits into
the current narrative. In practice, this comes down to finding the right
sections to edit. Although I have yet to apply this principle outside of the
Emacs configuration, I will try to incorporate the idea into my everyday
programming.

#+BEGIN_QUOTE
What should the narrative of my program look like?
#+END_QUOTE

This shift in focus essentially means that literate programmers are writers
first and programmers second. As someone who has seen increasing enjoyment in
writing documentation, I am very interested in pursuing the ideas of literate
programming further. For people like my younger self that saw documentation as a
chore, I expect that literate programming is utterly unappealing.

*** Refactoring
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingObservationsRefactoring-mwc1zi71ktj0
:END:

Due to having to create a narrative, literate programming requires knowing more
up front. Since I have written my Emacs configuration from scratch several
times, I was able to come up with something cohesive. However, moving around
pieces required significantly more refactoring effort. In areas that I'm less
familiar with, I would imagine that creating a fully literate program may not be
feasible or worth it.

*** Tooling
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingObservationsTooling-ecd1zi71ktj0
:END:

Org Mode has great tooling to export Org Mode files. There's support for Emacs
Lisp, markdown, and HTML. Writing an Org file is also a great literary
experience with Emacs containing many shortcuts. However, I noticed significant
tooling deficiencies when writing the Emacs Lisp parts of the program. The
functionality that I'm accustomed to was broken out of the box. This includes:

- Auto completion.
- Go to definition.
- Refactoring support like renaming a variable.

** Future Work
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingFutureWork-brd1zi71ktj0
:END:

*Will I migrate any of my real work to literate programming?*

No. The primary reason I would not use literate programming at work is that it
requires that other teammates be onboard. This is a big ask. I'm essentially
asking the team to become writers first and programmers second.

For solo work, I would still say mostly no. The main reason being that the
broken tooling would degrade my programming experience. Even then, I'm not
always in the literate mood. Sometimes I'm in the "get things done" mood.

*Will I continue to experiment with literate programming?*

Definitely. I will
- continue to think of my Emacs configuration as literature first.
- continue to explore Org Mode.
- think about what the narrative of my code is, even outside the context of a
  literate program.
- improve the readability/narrative of future literate programs. I'm mainly
  thinking about Python data science like work here.
- read some literate programs.


** References
:PROPERTIES:
:CUSTOM_ID: LiterateProgrammingReferences-57e1zi71ktj0
:END:

- [[https://www.youtube.com/watch?v=UCEzBNh9ufs][Dynamic Notebooks and Literate Programming - Sam Ritchie]] - London Clojurians
  YouTube channel.
- [[https://www.wmedrano.dev/literate-programs/emacs-config][My Literate Emacs Configuration]]
